import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon.ico" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/index.html" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/web-app-manifest-192x192.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/social-share-zen.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/apple-touch-icon.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon-96x96-v3.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon-v3.ico" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/_headers" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/apple-touch-icon-v3.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/web-app-manifest-512x512.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/site.webmanifest" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon-96x96.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/social-share.png" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon-v3.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/oc-theme-preload.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/favicon.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Script-Regular-D3wIWfF6.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pkl-u5AG7uiY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-mcp-bPG0WSCG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zht-DrgRcd3r.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/handlebars-BL8al0AC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/worker-DXsJPwkg.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/swift-Dg5xB15N.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/clojure-P80f7IUj.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nord-Ddv68eIx.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_AMS-Regular-DRggAlZN.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-09-8gNK4nDO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/systemd-4A_iFExJ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cpp-CofmeUqb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-06-BuvNosjK.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rosepine-DFf5RIYd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/da-DKIMy0WC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Regular-CTYiF6lA.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jison-wvAkD_A8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gnuplot-DdkO51Og.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/palenight-Djgtir2l.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/racket-BqYA7rlc.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/graphql-ChdNCCLP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/typespec-BGHnOYBU.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-light-high-contrast-BfjtVDDH.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Regular-wX97UBjC.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/viml-CJc9bBzg.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/python-B6aJPvgy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-server-Ddp6zL-8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zenscript-DVFEvuxE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/terraform-BETggiCN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/reg-C-SQnVFl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/perl-C0TMdlhV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/turtle-BsS91CYL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dracula-Bwy36Hqr.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-light-soft-hJgmCMqR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/monokai-BmT5Sw19.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/aurora-x-D-2ljcwZ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ko-Cz45-37g.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-manage-models-VF9UTBHj.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-dark-soft-CVdnzihN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-06-IqbtOTTn.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/plastic-3e1v2bzS.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Regular-Dr94JaBh.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cobalt2-DAVdkIoy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wasm-CG6Dc4jp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/raku-DXvB9xmW.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-02-B_yYorxz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size3-Regular-DgpXs0kz.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/poimandres-CS3Unz2-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-03-D3_ztwN2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ada-bCR0ucgS.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fr-BCCAzTHy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-model-unpaid-Cv5tW7bb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sdbl-DVxCFoDh.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rust-B1yitclQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-05-BNanGIjD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ts-tags-zn1MmPIZ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fortran-fixed-form-BZjJHVRy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/crystal-tKQVLTB8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vitesse-black-Bkuqu6BP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/apex-DDbsPZ6N.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ini-BEwlwnbL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vala-CsfeWuGM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-05-DZsXzrQW.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jsonnet-DFQXde-d.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-09-AXzGc7YL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/codeql-DsOJ9woJ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-frappe-BbhwKQAy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/docker-BcOcwvcX.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Regular-BNo7hRIc.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/actionscript-3-CfeIJUat.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/antigravity-m-mWKI7R.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-dark-default-Cuk6v7N8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Bold-CFMepnvq.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/typst-DHCkPAjA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-light-default-D7oLnXFd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-12-BJR1Ka3c.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kusto-BvAqAH-y.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-02-CS75AsoP.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dream-maker-BtqSS_iP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sas-cz2c8ADy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/home-DmPNBaWz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tokyonight-CbcoahaJ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/houston-DnULxvSX.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/plsql-ChMvpjG-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bs-C7sqWY8X.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vscode-C5BXgFjm.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wikitext-BhOHFoWU.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/orng-BM7q_Z0y.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-08-C6sK41fd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/amoled-CTKLNjMY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/session-q2JhBIlG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rst-B0xPkSld.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-dark-dimmed-DH5Ifo-i.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Regular-B22Nviop.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rel-C3B-1QV4.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-11-BjKpOuL0.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-04-Bi3-8HzN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-theme-D5KoaKCx.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/everforest-light-C8M2exoo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mermaid-DKYwYmdq.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tr-EOOdZMuM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cobol-nwyudZeR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/javascript-wDzz0qaB.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/snazzy-light-Bw305WKR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/verilog-BQ8w6xss.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-06-W4HuBYhb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-01-BuOD_o_q.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/move-Bu9oaDYs.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cmake-D1j8_8rp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/templ-W15q3VgB.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-04-CfVtpI7z.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dax-CEL-wOlO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/index-BZnoNB71.css" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/synthwave-84-CbfX1IO0.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-03-DK1yH6J2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/berry-uYugtg8r.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_AMS-Regular-DMm9YOAa.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/shaderlab-Dg9Lc6iA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jsx-g9-lgVsj.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/log-2UxHyX5q.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/openscad-C4EeE6gA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/splunk-BtCnVYZw.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/http-jrhK8wxY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ko-BYYQAwhd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jsonl-DcaNXYhu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zh-DqNk452I.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/proto-DyJlTyXw.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/synthwave84-mo9EICVe.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-03-Aug82oH0.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/asm-D_Q5rh1f.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ruby-BvKwtOVI.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-BoldItalic-iY-2wyZ7.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-BoldItalic-SpSLRI95.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/scss-OYdSNvt2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/puppet-BMWR74SV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mojo-1DNp92w6.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size2-Regular-oD1tc_U0.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ja-nNUG5Jbd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/diff-D97Zzqfu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ghostty-web-zHD73T1H.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/git-commit-F4YmCXRG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/red-bN70gL4F.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/th-GkB0dxVv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/powershell-Dpen1YoG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dracula-BzJJZx-M.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bibtex-CHM0blh-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zenburn-3iKGnI7X.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/html-GMplVEZG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-file-h52NLjZO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rose-pine-qdsjHGoJ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Italic-3WenGoN9.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Regular-CS6fqUqJ.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/lua-BbnMAYS6.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/night-owl-C39BiMTA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-latte-C9dUb6Cb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Bold-BsDP51OF.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/erlang-DsQrWhSR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-05-BVmKob0k.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/postcss-CXtECtnM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/th-BNDxfr9V.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kotlin-BdnUsdx6.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vitesse-light-CVO1_9PV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/blade-DVc8C-J4.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/julia-C8NyazO9.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/one-dark-pro-DVMEJ2y_.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-light-medium-DRw_LuNl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/de-W5dPqUFm.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-06-GK5Tqy6u.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tsv-B_m7g4N7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/angular-html-CU67Zn6k.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-dark-hard-CFHQjOhq.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Bold-Dq_IR9rO.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-08-CZowNquU.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cue-D82EKSYY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/everforest-dark-BgDCqdQA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/shellscript-Yzrsuije.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/smalltalk-BERRCDM3.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-settings-BaiCxBpC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/marko-CPi9NSCl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Regular-CTRA-rTL.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tcl-dwOrl1Do.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/one-light-PoHY5YXO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/glimmer-ts-U6CK756n.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-07-nvIV4VRE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-02-BIvWfOQf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vyper-CDx5xZoG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-01-BtRq6dLN.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wgsl-Dx-B1_4e.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gdresource-B7Tvp0Sc.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/osaka-jade-LSg9CtTT.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sparql-rVzFXLq3.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/light-plus-B7mTdjB0.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nginx-DknmC5AR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-01-Cv8FIGVN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/po-BTJTHyun.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ar-BBkUbD-U.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/desktop-BmXAJ9_W.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ru-BjHzBLo1.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/no-DQ9niEg2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jssm-C2t-YnRu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/__vite-browser-external-2447137e-BIHI7g3E.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-02-EygnDbCM.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/solidity-rGO070M0.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/onedarkpro-C4eYovZb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rose-pine-moon-D4_iv3hh.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-04-CmCNjd7G.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-07-0r0kiLGz.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/haxe-CzTSHFRz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/json-Cp-IABpG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/common-lisp-Cg-RD9OK.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/provider-icon-BP1kcVo2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/talonscript-CkByrt1z.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/solarized-dark-DXbdFlpD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bat-BkioyH1T.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size4-Regular-BF-4gkZK.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/csv-fuZLfV_i.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Italic-NWA7e6Wa.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gleam-BspZqrRM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fsharp-CXgrBDvD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/clarity-D53aC0YG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size2-Regular-Dy4dx90m.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-10-Ck5hR7zH.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tasl-QIJgUcNo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Bold-Jm3AIy58.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-mocha-D87Tk5Gz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gherkin-DyxjwDmM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-12-XTIkittV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-macchiato-DQyhUUbL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Regular-DDBCnlJ7.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-07-B2AcuX88.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/git-rebase-r7XF79zn.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/lean-Bc6EcWN3.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/astro-CbQHKStN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/apache-Pmp26Uib.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/coffee-Ch7k5sss.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/status-popover-body-D1ud7bJQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hjson-D5-asLiD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-04-BvTiGxWY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/markdown-Cvjx9yec.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/system-verilog-CnnmHF94.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cypher-COkxafJQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/xsl-CtQFsRM5.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sass-Cj5Yp3dK.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/llvm-BtvRca6l.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/soy-Brmx7dQM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/coq-DkFqJrB1.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-04-CrvHiQIe.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-provider-C_bBWJ3C.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/no-BdWkBMwo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/br-CZ3IHiCZ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/genie-D0YGMca9.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/java-CylS5w8V.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-05-DY6LpiuN.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/d-85-TOEBH.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-08-DBf7Bwjz.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/one-dark-Bjk1FzZz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jsonc-Des-eS-w.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zig-VOosw3JB.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vb-D17OF-Vu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/es-BKl1__G4.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/go-Dn2_MT6a.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ara-BRHolxvo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wolfram-lXgVvXCa.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/typescript-BPQ3VLAy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-10-E37zfY9y.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/awk-DMzUqQB5.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-04-CaGsIGFP.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nightowl-Pa1W3oWG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/imba-DGztddWO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bsl-BO_Y6i37.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nushell-C-sUppwS.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-fork-VbB5BONp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pierre-light-zjGsWSiE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-07-cqQEvbIf.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-CDQyWXdQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/objective-c-DXmwc3jG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-01-gmydkbKo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Bold-DbIhKOiC.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-macchiato-BG2vmDCz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/xml-sdJ4AIDG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kdl-DV7GczEv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/shadesofpurple-BtwY-YRg.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/aura-D4OP0z-q.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/latex-BdAV_C_H.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/liquid-DYVedYrR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pl-B1PbnQJF.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-light-hard-CH1njM8p.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fr-BGWW507w.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vesper-67WFNJYM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hy-DFXneXwc.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zht-CfMMeSr0.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ayu-dark-Cv9koXgw.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/toml-vGWfd6FD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Regular-CB_wures.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kanagawa-lotus-CfQXZHmo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dotenv-Da5cRb03.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/select-xP7sGfY1.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-D79fVyNx.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-03-BHLEoqSS.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/emacs-lisp-C9XAeP06.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/regexp-CDVJQ6XC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/logo-BtOb2qkB.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mercury-CL9KPSEM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hxml-Bvhsp5Yf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-theme-palenight-Csfq5Kiy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Script-Regular-C5JkGWo-.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-select-directory-COfpRwxb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-ukvyfYoH.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kanagawa-wave-DWedfzmr.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/solarized-light-L9t79GZl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-07-_-IkdLL4.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-05-CFi_H2fs.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/objective-cpp-CLxacb5B.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-theme-lighter-B0m2ddpp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/andromeeda-C-Jbm3Hp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mdx-Cmh6b_Ma.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-edit-project-CRyH0QEf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/list-DQex6FYM.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-BoldItalic-DzxPMmG6.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-theme-ocean-CyktbL80.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size4-Regular-Dl5lxZxV.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/polar-C0HS_06l.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-05-D2gbGoRH.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/powerquery-CEu0bR-o.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Bold-waoOVXN0.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-11-CVdXg8G-.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/min-light-CTRr51gU.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/luau-CXu1NL6O.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rose-pine-dawn-DHQR4-dF.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/index-Ae4klmX7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bicep-Bmn6On1c.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/jinja-4LBKfQ-Z.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-01-BJxg7Br3.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/qss-IeuSbFQv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tsx-COt5Ahok.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/elixir-CDX3lj18.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-BoldItalic-B3XSjfu4.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/twig-CO9l9SDP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ballerina-BFfxhgS-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vue-vine-8moa0y9V.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/groovy-gcz8RCvz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/zh-BvcGTnhx.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dark-plus-C3mMm8J8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/narrat-DRg8JJMk.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-10-84PPn2Zu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fish-BvzEVeQv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sql-BLtJtn59.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/stata-BH5u7GGu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/prolog-CbFg5uaA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/file-icon-BmLrtl_S.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gruvbox-dark-medium-GsRaNv29.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Regular-Di6jR-x-.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/razor-CE9lU5zL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hcl-BWvSN4gD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/html-derivative-BFtXZ54Q.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/abap-BdImnpbu.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-Italic-DA0__PXp.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mdc-DUICxH0z.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fortran-free-form-D22FLkUw.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-09-CidmJWaA.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ssh-config-_ykCGR6B.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-04-C7yadpJT.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/v-BcVCzyr7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Script-Regular-D5yQViql.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fennel-BYunw83y.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vesper-DU1UobuO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wit-5i3qLPDT.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Bold-BEiXGLvX.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hlsl-D3lLCCz7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bs-DggTjjbO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kanagawa-dragon-CkXjmgJE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dracula-soft-BXkSAIEj.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/de-BrAnvqUo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/haml-B8DHNrY2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/solarized-DsjFR-SU.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-06-CfV385SL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/da-Cs-ieDYR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/codeowners-Bp6g37R7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-dark-DHJKELXO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/everforest-DCRF6ST7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Italic-DN2j7dab.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Regular-Dxdc4cR9.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cairo-KRGpt6FW.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Bold-CL6g_b3V.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nim-CVrawwO9.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-06-DiKbyBF9.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yaml-Buea-lGh.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-08-HcI83CoX.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/glimmer-js-Rg0-pVw9.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/svelte-3Dk4HxPD.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/asciidoc-Dv7Oe6Be.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size1-Regular-C195tn64.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tex-CxkMU7Pf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-06-BAYmihXf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/server-row-DjDcgpyO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wasm-MzD3tlZU.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/slack-dark-BthQWCQV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/opencode-D7rBuNi7.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tokyo-night-hegEt444.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nix-c8nO5XWb.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/erb-BOJIQeun.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/scala-C151Ov-r.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/kanagawa-PkxnAgRP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vitesse-dark-D0r3Knsf.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/catppuccin-frappe-DFWUc33u.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ocaml-C0hk2d4L.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/br-CyKaxbmo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pug-CGlum2m_.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/carbonfox-DDZsuZPB.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-01-HWHtipgi.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cursor-CX4xD2IP.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/c-BIGW1oBm.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size1-Regular-Dbsnue_I.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-05-CuuaeyjC.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-02-CujvGF7f.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gdscript-DTMYz4Jt.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-03-DrFH92rH.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/switch-XocFhLy2.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-03-DXp7Zb0f.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dart-CF10PKvl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size4-Regular-DWFBv043.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/php-CDn_0X-4.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pascal-D93ZcfNL.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size3-Regular-CTq5MqoE.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/glsl-DplSGwfg.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-BoldItalic-DxDJ3AOS.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/dialog-connect-provider-C7vJ75uy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/android-studio-t3zZ7G0e.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-05-CrtAHyVr.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/wenyan-BV7otONQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-04-dSUw_8vI.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/alert-08-pIF0yjmQ.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-09-CxEgoAHQ.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/json5-C9tS-k6U.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/r-DiinP2Uv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/elm-DbKCFpqz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-01-SdbMMaiV.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-DYnPGtRk.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Italic-YYjJ1zSn.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vue-html-CChd_i61.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Bold-Cx986IdX.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Regular-ypZvNtVU.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/mipsasm-CKIfxQSi.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/material-theme-darker-BfHTSMKl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ja-DgbEFvKm.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/edge-BkV0erSs.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-06-Cj_2vOI4.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nextflow-BrzmwbiE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-BoldItalic-CZnvNsCZ.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_AMS-Regular-BQhdFMY1.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/make-CHLpvVh8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/haskell-Df6bDoY_.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pierre-dark-ClCaJvdG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/shellsession-BADoaaVG.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/cadence-Bv_4Rxtq.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Fraktur-Bold-BdnERNNW.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/fluent-C4IJs8-o.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/min-dark-CafNBF8u.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Typewriter-Regular-D3Ib7_Hf.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Typewriter-Regular-CO6r4hn1.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-Italic-flOr_0UB.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ar-DkvVq_vy.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-02-CzaO3Yrz.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/scheme-C98Dy4si.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/rosmsg-BJDFO7_C.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vercel-CzCqZjzn.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-03-BPb7xYJT.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/apl-dKokRX4l.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size1-Regular-mCD8mA8B.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/csharp-K5feNrxe.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Math-Italic-t53AETM-.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/matrix-wjRIPmmp.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/laserwave-DUszq2jm.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/angular-ts-BwZT4LLn.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nord-NfRmCUpk.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/qmldir-C8lEn-DE.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/less-B1dDrJ26.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Main-Italic-BMLOBm91.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-10-C1PuPJJ6.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/gdshader-DkwncUOv.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Bold-D1sUS0GD.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vhdl-CeAyd5Ju.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-04-olyHi8qQ.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Size2-Regular-B7gKUWhC.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/qml-3beO22l8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/applescript-Co6uUVPk.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/purescript-CklMAg4u.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/tr-DpetMpKH.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/bip-bop-07-BoG3Fd8O.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/prisma-Dd19v3D-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-light-DAi9KRSo.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_SansSerif-Italic-C3H0VqGB.woff2" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/css-DPfMkruS.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/flexoki-Cuz5xwiW.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Caligraphic-Bold-ATXxdsX0.ttf" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/monokai-D4h5O-jR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/nope-08-COPo0uNf.aac" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/beancount-k_qm7-4y.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/es-CVo2QaR5.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hack-CaT9iCJl.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/matlab-D7o27uSR.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sprite-Fb-TFjRY.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ru-Cz7sqdk-.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/ayu-C-7mtaZC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/KaTeX_Typewriter-Regular-C0xS9mPB.woff" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/sprite-B0ryth1W.svg" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/stylus-BEDo0Tqx.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/vue-DnHKYNfI.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/staplebops-02-dGmDElbO.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/pl-4Xap3szY.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/lucent-orng-3zCc1Xf5.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/hurl-irOxFIW8.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/riscv-BM1_JUlF.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/yup-03-DlJPYLhC.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/slack-ochin-DqwNpetd.js" with { type: "file" }
import "/Users/findly/other/testagent-opencode/packages/app/dist/assets/github-dark-high-contrast-E3gJ1_iC.js" with { type: "file" }
