#!/usr/bin/env bun

import { $ } from "bun"
import fs from "fs"
import path from "path"
import { fileURLToPath } from "url"
import solidPlugin from "@opentui/solid/bun-plugin"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import { Script } from "@opencode-ai/script"
import pkg from "../package.json"

// testagent_change start - parse flags early so --skip-models works before models block
const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")
const windowsFlag = process.argv.includes("--windows")
const skipModels = process.argv.includes("--skip-models")
const targetArg = process.argv.find((a) => a.startsWith("--target="))?.split("=")[1]
// testagent_change end

// testagent_change start - removed models.dev remote fetch, MODELS_DEV_API_JSON is required
if (!skipModels) {
  const modelsDataRaw = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : (() => {
        throw new Error("MODELS_DEV_API_JSON env var required: path to a local copy of the model catalog api.json")
      })()
  // Strip the opencode zen gateway provider from snapshot
  const modelsJson = JSON.parse(modelsDataRaw)
  delete modelsJson["opencode"]
  delete modelsJson["opencode-go"]
  const modelsData = JSON.stringify(modelsJson)
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.js"),
    `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
  )
  await Bun.write(
    path.join(dir, "src/provider/models-snapshot.d.ts"),
    `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
  )
  console.log("Generated models-snapshot.js")
} else {
  console.log("Skipping models snapshot generation (--skip-models)")
}
// testagent_change end

// Load migrations from migration directories
const migrationDirs = (
  await fs.promises.readdir(path.join(dir, "migration"), {
    withFileTypes: true,
  })
)
  .filter((entry) => entry.isDirectory() && /^\d{4}\d{2}\d{2}\d{2}\d{2}\d{2}/.test(entry.name))
  .map((entry) => entry.name)
  .sort()

const migrations = await Promise.all(
  migrationDirs.map(async (name) => {
    const file = path.join(dir, "migration", name, "migration.sql")
    const sql = await Bun.file(file).text()
    const match = /^(\d{4})(\d{2})(\d{2})(\d{2})(\d{2})(\d{2})/.exec(name)
    const timestamp = match
      ? Date.UTC(
          Number(match[1]),
          Number(match[2]) - 1,
          Number(match[3]),
          Number(match[4]),
          Number(match[5]),
          Number(match[6]),
        )
      : 0
    return { sql, timestamp, name }
  }),
)
console.log(`Loaded ${migrations.length} migrations`)

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
  {
    os: "linux",
    arch: "arm64",
  },
  {
    os: "linux",
    arch: "x64",
  },
  {
    os: "linux",
    arch: "x64",
    avx2: false,
  },
  {
    os: "linux",
    arch: "arm64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
  },
  {
    os: "linux",
    arch: "x64",
    abi: "musl",
    avx2: false,
  },
  {
    os: "darwin",
    arch: "arm64",
  },
  {
    os: "darwin",
    arch: "x64",
  },
  {
    os: "darwin",
    arch: "x64",
    avx2: false,
  },
  {
    os: "win32",
    arch: "arm64",
  },
  {
    os: "win32",
    arch: "x64",
  },
  {
    os: "win32",
    arch: "x64",
    avx2: false,
  },
]

const targets = targetArg
  ? allTargets.filter((item) => {
      const [os, arch, variant] = targetArg.split("-")
      if (item.os !== os) return false
      if (item.arch !== arch) return false
      if (variant === "baseline" && item.avx2 !== false) return false
      if (variant !== "baseline" && item.avx2 === false) return false
      return true
    })
  : singleFlag
    ? allTargets.filter((item) => {
        if (item.os !== process.platform || item.arch !== process.arch) {
          return false
        }
        if (item.avx2 === false) {
          return baselineFlag
        }
        if (item.abi !== undefined) {
          return false
        }
        return true
      })
    : windowsFlag // testagent_change
      ? allTargets.filter((item) => item.os === "win32") // testagent_change
      : allTargets

// testagent_change start - build app for offline web UI embedding
const appDir = path.resolve(dir, "../app")
const appDist = path.join(appDir, "dist")
console.log("Building app for embedding...")
if (!fs.existsSync(appDir)) {
  await $`bun run build`.cwd(appDir)
} else {
  console.log("App directory exists, skipping build. Delete the app/dist directory to force a rebuild.")
}
const appFiles = await Array.fromAsync(new Bun.Glob("**/*").scan({ cwd: appDist, onlyFiles: true }))
// appFiles are relative paths like "index.html", "assets/index-abc.js"
// We pass them to web.ts via define so it can map blob.name -> URL path
const appManifest = Object.fromEntries(appFiles.map((f) => [path.basename(f), "/" + f]))
console.log(`Found ${appFiles.length} app assets to embed`)

// Generate a shim that imports all app assets as embedded files.
// Using `with { type: "file" }` tells Bun to embed the raw bytes without
// trying to parse/bundle the content (critical for pre-built CSS/JS/fonts).
const shimLines = appFiles.map((f) => `import ${JSON.stringify(path.join(appDist, f))} with { type: "file" }`)
const shimPath = path.join(dir, "src/server/web-embed-shim.ts")
await Bun.write(shimPath, shimLines.join("\n") + "\n")
// testagent_change end

await $`rm -rf dist`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`

  const localPath = path.resolve(dir, "node_modules/@opentui/core/parser.worker.js")
  const rootPath = path.resolve(dir, "../../node_modules/@opentui/core/parser.worker.js")
  const parserWorker = fs.realpathSync(fs.existsSync(localPath) ? localPath : rootPath)
  const workerPath = "./src/cli/cmd/tui/worker.ts"

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/testagent`, // testagent_change
      execArgv: [`--user-agent=testagent/${Script.version}`, "--use-system-ca", "--"], // testagent_change - kept opencode for HTTP user-agent compatibility
      windows: {},
    },
    entrypoints: ["./src/index.ts", parserWorker, workerPath, shimPath],
    naming: { asset: "[name].[ext]" }, // testagent_change - preserve Vite hashes, disable Bun's extra hash layer
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OPENCODE_MIGRATIONS: JSON.stringify(migrations),
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_WORKER_PATH: workerPath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
      APP_MANIFEST: JSON.stringify(appManifest), // testagent_change - filename -> URL path map for web.ts
    },
  })

  // Smoke test: only run if binary is for current platform
  if (item.os === process.platform && item.arch === process.arch && !item.abi) {
    const binaryPath = `dist/${name}/bin/testagent` // testagent_change
    console.log(`Running smoke test: ${binaryPath} --version`)
    try {
      const versionOutput = await $`${binaryPath} --version`.text()
      console.log(`Smoke test passed: ${versionOutput.trim()}`)
    } catch (e) {
      console.error(`Smoke test failed for ${name}:`, e)
      process.exit(1)
    }
  }

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber --repo ${process.env.GH_REPO}`
}

export { binaries }
